# Generated by Django 5.2.7 on 2025-12-05 08:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batiment_chambre', models.CharField(choices=[('R+G1', 'R+G1'), ('R+F2', 'R+F2'), ('R+G3', 'R+G3'), ('R+F4', 'R+F4'), ('R+M1', 'R+M1'), ('R+GZ', 'R+GZ')], help_text='batiment aiza', max_length=4)),
                ('caract_chambre', models.TextField(help_text="mombamonra an'ilay efitra.")),
                ('etage_chambre', models.CharField(max_length=20)),
                ('prix_chambre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_chambre', models.CharField(choices=[('DISPO', 'Disponible'), ('OCCUP', 'Occupee'), ('BPOS', 'Bientot Dispo'), ('HS', 'Hors Service')], default='DISPO', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule_etudiant', models.CharField(help_text='Tsy maintsy fenoina ity', max_length=20, unique=True)),
                ('nom_etudiant', models.CharField(help_text='Anarana', max_length=100)),
                ('prenom_etudiant', models.CharField(help_text="Fanampin'anarana", max_length=100)),
                ('mention_etudiant', models.CharField(choices=[('INFO', 'Informatique'), ('MATHS', 'Mathematique'), ('COMM', 'Communication'), ('AGRO', 'Agronomie')], help_text='Ny mention anao', max_length=5)),
                ('niveauactu_etudiant', models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1'), (5, 'M2')])),
                ('tel_etudiant', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatriculeEnregistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(help_text='Matricule azo ekena', max_length=20, unique=True)),
                ('is_used', models.BooleanField(default=False, help_text="Efa nampiasaina ve ity ho an'ny User iray")),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_cible', models.IntegerField(choices=[(1, 'L1'), (2, 'L2'), (3, 'L3'), (4, 'M1'), (5, 'M2')], help_text='Niveau tadiavina')),
                ('date_voulu', models.DateField(help_text="Date tiana hidirana amun'ilay efitra")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('statut_reserva', models.CharField(choices=[('ATT', 'En attente'), ('VAL', 'Valide'), ('ANNUL', 'Annule')], default='ATT', max_length=5)),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AGLU.chambre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGLU.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_paiement', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_paiement', models.CharField(choices=[('MOIS', 'Mensuel'), ('ANNEE', 'Annuel')], max_length=5)),
                ('date_paiement', models.DateField(default=django.utils.timezone.now)),
                ('statut_paiement', models.CharField(choices=[('PAYE', 'Paye'), ('IMPAYE', 'Impaye'), ('PARTIEL', 'Partiel')], default='IMPAYE', max_length=7)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AGLU.reservation')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_etudiant', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
